### ISSUE TITLE
Django 1.7+ support

### ISSUE THREAD

**Issue by oblalex** [oblalex/django-candv-choices#7]
Model migrations from Django 1.8 do not work causing the following crash:

```
D:\PYTHON\Projects\rof-stats-backend>python manage.py makemigrations squads
C:\Python34\lib\importlib\_bootstrap.py:321: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
 return f(*args, **kwds)

Traceback (most recent call last):
 File "C:\Python34\lib\site-packages\django\db\migrations\state.py", line 348, in from_model
   fields.append((name, field_class(*args, **kwargs)))
 File "C:\Python34\lib\site-packages\candv_x\django\choices\db.py", line 22, in __init__
   assert issubclass(choices, ConstantsContainer)
TypeError: issubclass() arg 1 must be a class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "manage.py", line 12, in <module>
   execute_from_command_line(sys.argv)
 File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 338, in execute_from_command_line
   utility.execute()
 File "C:\Python34\lib\site-packages\django\core\management\__init__.py", line 330, in execute
   self.fetch_command(subcommand).run_from_argv(self.argv)
 File "C:\Python34\lib\site-packages\django\core\management\base.py", line 390, in run_from_argv
   self.execute(*args, **cmd_options)
 File "C:\Python34\lib\site-packages\django\core\management\base.py", line 441, in execute
   output = self.handle(*args, **options)
 File "C:\Python34\lib\site-packages\django\core\management\commands\makemigrations.py", line 99, in handle
   ProjectState.from_apps(apps),
 File "C:\Python34\lib\site-packages\django\db\migrations\state.py", line 178, in from_apps
   model_state = ModelState.from_model(model)
 File "C:\Python34\lib\site-packages\django\db\migrations\state.py", line 354, in from_model
   e,
TypeError: Couldn't reconstruct field coalition on squads.Squad: issubclass() arg 1 must be a class
```

This happens because for some reason `__init__` method of the field is invoked multiple times for some reason. And 2nd it is given a list of constants from container.

**Comment by oblalex** [comment]
DB field must provide [deconstruct()](https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#field-deconstruction) method to fix this.
